use_frameworks!

platform :ios, '8.0'

target 'ZGStar_Example' do
  pod 'ZGStar', :path => '../'

  target 'ZGStar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
